---
AWSTemplateFormatVersion: "2010-09-09"

Description: |
  Creates a stack containing an IAM role used to grant access to a repository create resources.

Parameters:
  Repository:
    Type: String
    Description: |
      Repository name with organization. For example, rafaelsvieira/labs-eks-foundation.

Resources:
  FoundationRepoRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: labs-eks-foundation-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated:
                - !Sub "arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com"
            Action:
              - sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: "sts.amazonaws.com"
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub "repo:${Repository}:*"
      Policies:
        - PolicyName: ManageRole
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "iam:CreatePolicy"
                  - "iam:UpdateRoleDescription"
                  - "iam:DeletePolicy"
                  - "iam:CreateRole"
                  - "iam:DeleteRole"
                  - "iam:UpdateRole"
                  - "iam:PutRolePolicy"
                Resource:
                  - !Sub "arn:aws:iam::${AWS::AccountId}:policy/*"
                  - !Sub "arn:aws:iam::${AWS::AccountId}:role/*"
Outputs:
  RoleId:
    Description: The logical ID of the IAM role
    Value: !Ref FoundationRepoRole
  RoleArn:
    Description: The ARN of the IAM role
    Value: !GetAtt [FoundationRepoRole, Arn]
